apiVersion: v1
kind: Service
metadata:
  name: spring-boot-svc
  labels:
    app: spring-boot-api
spec:
  selector:
    app: spring-boot-api
  type: LoadBalancer
  ports:
    - nodePort: 31000
      port: 80
      targetPort: 8080